#!/bin/bash

# default test cases
cases="case-1"

if [ ! -z $1 ];then
    cases=$1
fi
errors=0

for case in $cases
do
    out=$(ansible-playbook ./tests/site.yml -i ./tests/hosts -t $case -D -e systemd_service_root_dir=$case)
    result=$?
    if echo $out|tail -n 2 |grep " changed=0 " >/dev/null
    then
        echo -n "."
    else
        echo $case
        echo
        echo "$out"
        errors=$(( errors+1 ))
    fi
done

if [ $errors -eq 0 ]
then
    echo " ok"
else
    echo "${errors} error(s)"
fi
exit $errors
